"""audio media fields

Revision ID: 096cebe99ba6
Revises: e3c4d5f6a7b8
Create Date: 2026-07-17 01:48:32.402902
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '096cebe99ba6'
down_revision: Union[str, None] = 'e3c4d5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mime', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('duration_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tg_file_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_column('tg_file_id')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('duration_sec')
        batch_op.drop_column('mime')
        batch_op.drop_column('media_filename')

    # ### end Alembic commands ###
