"""initial schema

Revision ID: 53c263344913
Revises: 
Create Date: 2026-07-08 12:56:14.386343
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53c263344913'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('client_intro', sa.Text(), nullable=False),
    sa.Column('start_button', sa.String(length=64), nullable=False),
    sa.Column('reference_period', sa.String(length=64), nullable=False),
    sa.Column('answer_scale', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('soft_threshold', sa.Integer(), nullable=False),
    sa.Column('soft_no_leading', sa.Text(), nullable=False),
    sa.Column('tie_priority', sa.JSON(), nullable=False),
    sa.Column('no_show', sa.JSON(), nullable=False),
    sa.Column('must_include', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_static_texts',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('modules',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('content_version', sa.String(length=32), nullable=False),
    sa.Column('final_product_kind', sa.String(length=32), nullable=False),
    sa.Column('postmodule_kind', sa.String(length=16), nullable=False),
    sa.Column('passport', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('week_n', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('day_range', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('final_product_templates',
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('module_code')
    )
    op.create_table('intake_directions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name_short', sa.String(length=255), nullable=False),
    sa.Column('name_leading', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('tie_priority', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('intake_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('leading', sa.String(length=16), nullable=False),
    sa.Column('focus1', sa.String(length=16), nullable=True),
    sa.Column('focus2', sa.String(length=16), nullable=True),
    sa.Column('is_soft', sa.Boolean(), nullable=False),
    sa.Column('chosen_module_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intake_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_results_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=True),
    sa.Column('week_n', sa.Integer(), nullable=True),
    sa.Column('day_n', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)

    op.create_table('markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', 'phase', 'idx')
    )
    op.create_table('module_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('intro_screen', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('key_themes', sa.JSON(), nullable=False),
    sa.Column('intent_questions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', 'n')
    )
    op.create_table('postmodule_config',
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('module_code')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_table('critical_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('refs', sa.JSON(), nullable=False),
    sa.Column('min_hits', sa.Integer(), nullable=False),
    sa.Column('additional_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['module_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('week_n', sa.Integer(), nullable=False),
    sa.Column('day_n', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('morning_answers', sa.JSON(), nullable=False),
    sa.Column('task_status', sa.String(length=16), nullable=True),
    sa.Column('task_answer', sa.JSON(), nullable=True),
    sa.Column('quiz_answer', sa.Text(), nullable=True),
    sa.Column('evening_answers', sa.JSON(), nullable=False),
    sa.Column('reflection_answers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'week_n', 'day_n')
    )
    op.create_table('final_product_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('saved_content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flag_accumulator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=False),
    sa.Column('total_weight', sa.Integer(), nullable=False),
    sa.Column('weeks_hit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'tag')
    )
    op.create_table('intake_interps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_code', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('client_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['direction_code'], ['intake_directions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction_code', 'slot')
    )
    op.create_table('intake_questions',
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('direction_code', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['direction_code'], ['intake_directions.code'], ),
    sa.PrimaryKeyConstraint('n')
    )
    op.create_table('module_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_n', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('task_subtasks', sa.JSON(), nullable=False),
    sa.Column('quiz', sa.JSON(), nullable=False),
    sa.Column('reflection', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['module_weeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'day_n')
    )
    op.create_table('postmodule_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('topic_scores', sa.JSON(), nullable=False),
    sa.Column('recommended_modules', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selfcheck_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('q_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['module_weeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'q_index')
    )
    op.create_table('selfcheck_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('week_n', sa.Integer(), nullable=False),
    sa.Column('core_score', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('triggered_criticals', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_interps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('score_min', sa.Integer(), nullable=False),
    sa.Column('score_max', sa.Integer(), nullable=False),
    sa.Column('sys_action', sa.String(length=32), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('user_text', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['module_weeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'zone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_interps')
    op.drop_table('selfcheck_results')
    op.drop_table('selfcheck_questions')
    op.drop_table('postmodule_results')
    op.drop_table('module_days')
    op.drop_table('intake_questions')
    op.drop_table('intake_interps')
    op.drop_table('flag_accumulator')
    op.drop_table('final_product_instances')
    op.drop_table('daily_entries')
    op.drop_table('critical_triggers')
    op.drop_table('user_identities')
    op.drop_table('postmodule_config')
    op.drop_table('module_weeks')
    op.drop_table('markers')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('intake_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_results_user_id'))

    op.drop_table('intake_results')
    op.drop_table('intake_directions')
    op.drop_table('final_product_templates')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_id'))

    op.drop_table('enrollments')
    op.drop_table('audio_assets')
    op.drop_table('users')
    op.drop_table('modules')
    op.drop_table('intake_static_texts')
    op.drop_table('intake_config')
    # ### end Alembic commands ###
