"""enrollment mode

Revision ID: ba9717516ebd
Revises: 53c263344913
Create Date: 2026-07-08 13:35:51.745809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba9717516ebd'
down_revision: Union[str, None] = '53c263344913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=8), nullable=False, server_default='normal'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
